"""
Esmerald settings for nprOlusolaBe project.

Generated by 'esmerald createproject' using Esmerald 3.4.0.
"""

from typing import Optional
from functools import cached_property
from esmerald.conf.enums import EnvironmentType

from nprOlusolaBe.configs.production.settings import AppSettings


class TestingAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "API application in testing mode."
    environment: Optional[str] = EnvironmentType.TESTING
    @cached_property
    def get_database_url(self) -> str:
        return f"{self.db_driver}://{self.db_user}:{self.db_password}@{self.db_host}:{self.db_port}/{self.db_name}_testing"
