"""
Esmerald settings for nprOlusolaBe project.

Generated by 'esmerald createproject' using Esmerald 3.4.0.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType

from nprOlusolaBe.configs.production.settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "API application in development mode."
    environment: Optional[str] = EnvironmentType.DEVELOPMENT
