"""empty message

Revision ID: c7eba0eaaef9
Revises: c838868e86c2
Create Date: 2025-01-15 16:18:48.352500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7eba0eaaef9'
down_revision = 'c838868e86c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('name', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('company', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
