"""empty message

Revision ID: c838868e86c2
Revises: 
Create Date: 2025-01-07 15:35:07.678613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c838868e86c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogcategorys',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogtags',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('title', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medias',
    sa.Column('url', sa.String(length=400), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.String(length=150), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('newsletters',
    sa.Column('email', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productcategorys',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blogs',
    sa.Column('title', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('image', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('is_publish', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('category', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('label', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category'], ['blogcategorys.id'], name='fk_blogs_blogcategorys_category', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['image'], ['medias.id'], name='fk_blogs_medias_image', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['label'], ['labels.id'], name='fk_blogs_labels_label', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('title', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('image', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.Time(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.Time(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('url', sa.String(length=2005), autoincrement=False, nullable=True),
    sa.Column('location', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image'], ['medias.id'], name='fk_events_medias_image', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallerys',
    sa.Column('title', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('label', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('image', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image'], ['medias.id'], name='fk_gallerys_medias_image', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['label'], ['labels.id'], name='fk_gallerys_labels_label', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('user', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('order_items', sa.JSON(), autoincrement=False, nullable=False),
    sa.Column('orderId', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('CANCELLED', 'COMPLETED', 'PENDING', 'READY_FOR_SHIPMENT', 'SHIPPED', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_orders_users_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('image', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('external_links', sa.JSON(), autoincrement=False, nullable=False),
    sa.Column('meta_data', sa.JSON(), autoincrement=False, nullable=False),
    sa.Column('author', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('category', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('is_trash', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', 'LIMITED_STOCK', name='productstatus'), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name='fk_products_users_author', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category'], ['productcategorys.id'], name='fk_products_productcategorys_category', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image'], ['medias.id'], name='fk_products_medias_image', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('reviewer', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('is_accepted', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewer'], ['users.id'], name='fk_reviews_users_reviewer', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('image', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image'], ['medias.id'], name='fk_testimonials_medias_image', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogcomments',
    sa.Column('user', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('blog', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog'], ['blogs.id'], name='fk_blogcomments_blogs_blog', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_blogcomments_users_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloglikes',
    sa.Column('author', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('blog', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name='fk_bloglikes_users_author', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog'], ['blogs.id'], name='fk_bloglikes_blogs_blog', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('user', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('product', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product'], ['products.id'], name='fk_carts_products_product', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_carts_users_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('reference', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('order', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('user', sa.Uuid(), autoincrement=False, nullable=True),
    sa.Column('promo_code', sa.JSON(), autoincrement=False, nullable=False),
    sa.Column('extra_data', sa.JSON(), autoincrement=False, nullable=False),
    sa.Column('payment_url', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('is_trash', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order'], ['orders.id'], name='fk_payments_orders_order', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_payments_users_user', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('carts')
    op.drop_table('bloglikes')
    op.drop_table('blogcomments')
    op.drop_table('testimonials')
    op.drop_table('reviews')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('gallerys')
    op.drop_table('events')
    op.drop_table('blogs')
    op.drop_table('users')
    op.drop_table('productcategorys')
    op.drop_table('newsletters')
    op.drop_table('medias')
    op.drop_table('labels')
    op.drop_table('blogtags')
    op.drop_table('blogcategorys')
    # ### end Alembic commands ###
