from esmerald import Gateway
from esmerald.utils.module_loading import import_string


route_patterns = [
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.auth.v1.router.AuthAPIView",
        ),
        name="auth",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.account.v1.router.AccountAPIView",
        ),
        name="account",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.blog.v1.router.BlogAPIView",
        ),
        name="blog",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.blog.v1.router.BlogCategoryAPIView",
        ),
        name="blog_category",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.blog.v1.router.BlogTagAPIView",
        ),
        name="blog_tag",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.blog.v1.router.BlogCommentAPIView",
        ),
        name="blog_comment",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.blog.v1.router.BlogLikeAPIView",
        ),
        name="blog_like",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.event.v1.router.EventAPIView",
        ),
        name="event",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.gallery.v1.router.GalleryAPIView",
        ),
        name="gallery",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.label.v1.router.LabelAPIView",
        ),
        name="label",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.news_letter.v1.router.NewsLetterAPIView",
        ),
        name="news_letter",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.product.v1.router.ProductAPIView",
        ),  
        name="products",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.product.v1.router.ProductCategoryAPIView",
        ),  
        name="products",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.cart.v1.router.CartAPIView",
        ),
        name="cart",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.contact.v1.router.ContactAPIView",
        ),
        name="contact",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.reviews.v1.router.ReviewAPIView",
        ),
        name="reviews",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.testimonials.v1.router.TestimonialAPIView",
        ),
        name="testimonial",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.media.v1.router.MediaAPIView",
        ),
        name="media",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.orders.v1.router.OrderAPIView",
        ),
        name="orders",
    ),
    Gateway(
        handler=import_string(
            "nprOlusolaBe.apps.payment.v1.router.PaymentAPIView",
        ),
        name="payment",
    ),
]
