PAGINATION_LIMIT: int = 10
PAGINATION_OFFSET: int = 0
PAGINATION_PAGE: int = 1
PAGINATION_PAGE_SIZE: int = 10
MAX_PAGINATION_LIMIT: int = 50
MIN_PAGINATION_LIMIT: int = 1
DEFAULT_SORT_ORDER: str = "id"
